name: main

on: [push, pull_request]

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Configure Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node_modules
        id: cache-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ matrix.node-version }}-${{ runner.OS }}-build-${{ hashFiles('package.json') }}

      - name: Install npm in version ${{ matrix.node-version }}
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: npm install

      - name: Run test in version ${{ matrix.node-version }}
        run: npm run test:coverage
        env:
          CI: true

      - name: upload coverage artifact v${{ matrix.node-version }}
        uses: actions/upload-artifact@v2
        with:
          name: coveragev-${{ matrix.node-version }}
          path: ./coverage/lcov.info

  coverage:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: coveragev-12.x
          path: coverage
      - name: Generate coverage in coverall
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build application
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      # - name: Discord notification - start build
      #   uses: rjstone/discord-webhook-notify@v1.0.4
      #   with:
      #     severity: info
      #     text: ${{github.repository}} - ${{github.workflow}}
      #     details: '- **Pipeline:** https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}'
      #     webhookUrl: ${{ secrets.DISCORD_CHANNEL_WEBHOOK }}
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "12"

      - name: Cache node_modules
        id: cache-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: 12.x-${{ runner.OS }}-build-${{ hashFiles('package.json') }}

      - name: Install NPM
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: npm install

      - name: Build application
        run: npm run build

      - name: "Automated Version Bump"
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: "phips28/gh-action-bump-version@master"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          skip-tag: "true"

      - name: Generate dist artifact v${{ matrix.node-version }}
        uses: actions/upload-artifact@v2
        with:
          name: dist-folder
          path: dist/**/*
          if-no-files-found: error

  publish:
    name: NPM package publish
    needs:
      - build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: dist-folder
          path: .

      - id: release
        name: Release tag
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: patch

      - name: Publish on NPM
        uses: mikeal/merge-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      # - name: Notify discord
      #   if: success()
      #   uses: rjstone/discord-webhook-notify@v1.0.4
      #   with:
      #     severity: success
      #     description: Deploy finished - new release deployed
      #     details: |

      #       **- Tag name:** ${{ steps.release.outputs.tag_name }}
      #       **- Release version:** ${{ steps.release.outputs.version }}
      #     webhookUrl: ${{ secrets.DISCORD_CHANNEL_WEBHOOK }}
      # - name: Discord notification - Github generated release (error)
      #   if: failure()
      #   uses: rjstone/discord-webhook-notify@v1.0.4
      #   with:
      #     severity: error
      #     description: Github generated release failed (But deployed was done)
      #     webhookUrl: ${{ secrets.DISCORD_CHANNEL_WEBHOOK }}
      # - name: Discord notification - Github generated release (cancelled)
      #   if: cancelled()
      #   uses: rjstone/discord-webhook-notify@v1.0.4
      #   with:
      #     severity: warn
      #     description: Github generated release cancelled (But deployed was done)
      #     webhookUrl: ${{ secrets.DISCORD_CHANNEL_WEBHOOK }}
